version: '3.8'
services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_DRIVER=${DB_DRIVER}
      - DB_SOURCE=${DB_SOURCE}
      - SERVER_PORT=8080
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: skillswap_db
    ports:
      - "3306:3306"

