import { library } from "@fortawesome/fontawesome-svg-core";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";

// Import all icons that were in the original code
import {
  faUser,
  faSignOutAlt,
  faHome,
  faSearch,
  faComments,
  faEnvelope,
  faEye,
  faEyeSlash,
  faCode,
  faFilter,
  faChevronUp,
  faChevronDown,
  faExclamationCircle,
  faTimes,
  faHistory,
  faStar,
  faStarHalfAlt,
  faArrowRight,
  faBellSlash,
  faMusic,
  faUtensils,
  faPalette,
  faPenFancy,
  faGuitar,
  faLanguage,
  faCog,
  faVideo,
  faUpload,
  faFilm,
  faSpinner,
  faCheckCircle,
  faPlay,
  faPlayCircle,
  faDownload,
  faCoins,
  faCalendarAlt,
  faGraduationCap,
  faExchangeAlt,
  faComment,
  faCommentAlt,
  faPaperPlane,
  faSync,
  faArrowUp,
  faArrowDown,
  // Job posting icons
  faBriefcase,
  faBuilding,
  faMapMarkerAlt,
  faExternalLinkAlt,
  faBookmark,
  faMoneyBillAlt,
  faPlus,
  faPlusCircle,
  faCheck,
  faArrowLeft,
  faUndo,
} from "@fortawesome/free-solid-svg-icons";

// Register icons function
export function registerIcons(app) {
  // Add all icons to library
  library.add(
    faUser,
    faSignOutAlt,
    faHome,
    faSearch,
    faComments,
    faEnvelope,
    faEye,
    faEyeSlash,
    faCode,
    faFilter,
    faChevronUp,
    faChevronDown,
    faExclamationCircle,
    faTimes,
    faHistory,
    faStar,
    faStarHalfAlt,
    faArrowRight,
    faBellSlash,
    faMusic,
    faUtensils,
    faPalette,
    faPenFancy,
    faGuitar,
    faLanguage,
    faCog,
    faVideo,
    faUpload,
    faFilm,
    faSpinner,
    faCheckCircle,
    faPlay,
    faPlayCircle,
    faDownload,
    faCoins,
    faCalendarAlt,
    faGraduationCap,
    faExchangeAlt,
    faComment,
    faCommentAlt,
    faPaperPlane,
    faSync,
    faArrowUp,
    faArrowDown,
    faBriefcase,
    faBuilding,
    faMapMarkerAlt,
    faExternalLinkAlt,
    faBookmark,
    faMoneyBillAlt,
    faPlus,
    faPlusCircle,
    faCheck,
    faArrowLeft,
    faUndo,
  );

  // Register the FontAwesomeIcon component
  app.component("font-awesome-icon", FontAwesomeIcon);
}
